--- pyproject.toml.orig	2026-01-01 17:18:19 UTC
+++ pyproject.toml
@@ -7,7 +7,7 @@ authors = [
     { name = "Matrix.org Team and Contributors", email = "packages@matrix.org" }
 ]
 requires-python = ">=3.10.0,<4.0.0"
-license = "AGPL-3.0-or-later OR LicenseRef-Element-Commercial"
+license = { text = "AGPL-3.0-or-later OR LicenseRef-Element-Commercial" }
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Topic :: Communications :: Chat",
@@ -381,7 +381,7 @@ sqlglot = ">=28.0.0"
 # runtime errors caused by build system changes.
 # We are happy to raise these upper bounds upon request,
 # provided we check that it's safe to do so (i.e. that CI passes).
-requires = ["poetry-core>=2.0.0,<=2.1.3", "setuptools_rust>=1.3,<=1.11.1"]
+requires = ["poetry-core>=2.0.0", "setuptools_rust>=1.3"]
 build-backend = "poetry.core.masonry.api"
 
 
